# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('class_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('class_content', models.CharField(max_length=1000)),
                ('target_user', models.CharField(max_length=400)),
                ('tag', models.CharField(choices=[('program', 'Program'), ('base_subject', 'Base_Subject'), ('sport', 'Sport')], max_length=20)),
            ],
        ),
    ]
